spring.application.name=library-api

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/library_db

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.attqs.library_api=DEBUG
logging.level.org.mongodb.driver=WARN

# Jackson Configuration
spring.jackson.serialization.indent_output=true
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.default-property-inclusion=non_null

# Validation
spring.validation.enabled=true
